language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
script:
- cd Checkout.ApiClient.NetCore.Tests
- dotnet restore
- dotnet build
- dotnet test
env:
  global:
  - secure: Ya+YKF8Jr0LdKbGcmhYTbEwBtd4ryUjXlZWJY58+06ZhXVt7MsfMr4tTaSg69Ph0m7PCLdwl9JxZfUXdJGAcldG4A67nVo1qFPk8UkqDHKn+ak4BvqfSEaOr4+HX8p8+uO//ePLrT7EhTujruN84EuVg2KPQcuUOrH+pcyEUHIU3WMg0ohKfoTmolAK0yOHfywHHHFVAgggAcgxkoTq9JyFroI2Gmz76cZlmixvgVXDThrCkecJePeE5orAmHzZ1BT/M9h8Xxqu35n0OZkaGUVypvl/lfvhilq5EPpCKbAefE53Yr1kKxrJoJSnL2vQA3pn29zOEu0T3FRU/IOIOrrWJmYVRNtbY04MHCiLFhaw7CieXy74B/vH+W9Ah0OTLzJFZeSKyfSF2Y9Ag/UjUdkRhyqXiS7Ecmj+jjSJwPJGZxeY4w9Ed1UdExul6vCLJVmujDvzz6Y0fWHFwxP37n7/LdvM1te65KMowknwZnVt315hmiwQkZln5IuV2aQgOZTTrZHGGzXond48QroJOvenY7X45MWUkjzbATHItLjVy2jJ0J1cT4QLdbv0ewls+LE6SFwj5aeMyvHU/8+nhSZn94JbxXw2ABOZeRSIO7EXe+LXsDWAyXODOFe539MMKsCeQCxAnM8CR3U8zLKxTIxVnaqNlcArqmD+Dc4wjDkE=
  - secure: HzBiPzTXMPFUx+2xsTpiY6kTT/J4EGoyhub2EpGle7GX3XMTTIoR4vq6dbCeDOCZSsbIYFQGItaE44kd3NowTu0efEIsMId011YGFilJ8uvkdggq4V87O2MP+cHu2qI0bkfB3gS9Z9aDvhydXMceHeR8339N7Z9viSBILd5mreiBJn0VVtqUMquywnNObboO515nZDfzrhxLb+bXDTcHTwV4bQt2uOZjo/U3kmEexKZPYg60JVk0MkRqB/XKxW9W6+xMk90BxqotXfu5+Yr+HKRgmN2xj7P8+hnUg1pr4GnLxuf/dYBBmsWu5bnw3WPUHQ1H09FpWJKLoheMahpkqLtqtEzEg1J8HZ9U3xWPHeGYRYj2oOVuC3STSmUeTkKC3ML30SI0eBaHUy9IXxN64WptXYGGlxS26Hg9LeOP7eO0RGwoI1hc4X+0/xM29+7Zmz3DFUw9a8Y5/UhJ00kaDdiEs0CA+vASWapr+AKYr0nHe3WUM+PWCYsK4OV5u2JbDNJ2VVNvWMgHZVlo+PSspP7BzIdxDVavOyfybRktBvI4wabgZ2ISEUy/7inOoWlYdIXDB8Wr/b1LnfV3qDfOxDk8qxmAOr/6b4SwcbqQNRuUxm6hzHDK5HGFP41YXT37GzARknbHMo8ZbtSvrA34N6HXpNVJ3lI48Oj+4qK3tgY=